# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "sys-unstable-${version}";
  version = "2016-12-14";
  rev = "d75a52659825e75fff6158388dddc6a5b04f9ba5";

  goPackagePath = "golang.org/x/sys";

  src = fetchgit {
    inherit rev;
    url = "https://go.googlesource.com/sys";
    sha256 = "0zbv11kq5d8dxiddd4kzr785gbwb7x8d7lq4rqs5s7s43h0pl3x7";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
